"""Loopy belief propagation for data association (Williams & Lau 2014), TVT T4.

Targets (sources) i = 1..I, measurements j = 1..J. Weights w[i, 0] (source missed) and
w[i, j] (source i generated measurement j, as a likelihood ratio against clutter); a measurement
is generated by at most one source or is clutter (weight 1). Messages
    mu_{i->j} = w[i, j] / (w[i, 0] + sum_{j' != j} w[i, j'] nu_{j'->i}),
    nu_{j->i} = 1 / (1 + sum_{i' != i} mu_{i'->j}),
iterated from nu = 1; marginals p(a_i = j) ~ w[i, j] nu_{j->i}, p(a_i = 0) ~ w[i, 0].
``exact_marginals`` enumerates all joint associations (reference for small problems).
"""

from __future__ import annotations

import itertools

import numpy as np


def bp_marginals(w0: np.ndarray, w: np.ndarray, iters: int = 50, tol: float = 1e-9) -> tuple[np.ndarray, np.ndarray]:
    """w0 [I] (missed weights), w [I, J]. Returns beta [I, J + 1] (column 0 = missed) and the clutter probability [J]."""
    I, J = w.shape
    if I == 0 or J == 0:
        b = np.zeros((I, J + 1))
        b[:, 0] = 1.0
        return b, np.ones(J)
    nu = np.ones((I, J))
    mu = np.zeros((I, J))
    for _ in range(iters):
        s = w0[:, None] + (w * nu).sum(1, keepdims=True) - w * nu
        mu_new = w / np.maximum(s, 1e-300)
        tot = mu_new.sum(0, keepdims=True)
        nu_new = 1.0 / (1.0 + tot - mu_new)
        done = np.max(np.abs(nu_new - nu)) < tol
        mu, nu = mu_new, nu_new
        if done:
            break
    p = np.concatenate([w0[:, None], w * nu], 1)
    p = p / np.maximum(p.sum(1, keepdims=True), 1e-300)
    clutter = 1.0 / (1.0 + (mu * 1.0).sum(0)) if I else np.ones(J)
    return p, clutter


def exact_marginals(w0: np.ndarray, w: np.ndarray) -> np.ndarray:
    """Brute-force marginals over all valid joint associations (small I, J)."""
    I, J = w.shape
    out = np.zeros((I, J + 1))
    Z = 0.0
    for a in itertools.product(range(J + 1), repeat=I):
        used = [x for x in a if x > 0]
        if len(used) != len(set(used)):
            continue
        pr = 1.0
        for i, x in enumerate(a):
            pr *= w0[i] if x == 0 else w[i, x - 1]
        Z += pr
        for i, x in enumerate(a):
            out[i, x] += pr
    return out / Z
