"""Paper 2 validation table (second review): single-epoch estimator vs single-epoch PEB at 6 fixed geometries.

From results/P2/diag_rmse_vs_peb_<set>.json (scripts/p2_diag_rmse_vs_peb.py: 500 independent
noise + hardware draws per cell through the frozen single-epoch estimator, no EKF), MAIN hardware
(sigma_sync 1 ns, sigma_phi 2 deg), 400 and 100 MHz, TDoA, blocked LoS variant (b). Per geometry:
mount, LoS state (both LoS / blocked O-RUs), UE x [m]; per bandwidth: single-epoch LoS-only PEB,
bias magnitude ||E[p_hat] - p||, centred RMS sqrt(E||p_hat - E[p_hat]||^2), total RMSE
sqrt(E||p_hat - p||^2), all in cm (sample moments over the draws). Checks
RMSE^2 = bias^2 + centred^2 (exact identity of sample moments; reported as the maximum relative
deviation). Writes paper2/tables/validation.tex (booktabs rows only) and
results/P2/validation_table_<set>.json.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for p in (ROOT, ROOT / "scripts"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--set", default="heldout2")
    args = ap.parse_args()
    cells = json.loads((ROOT / "results" / "P2" / f"diag_rmse_vs_peb_{args.set}.json").read_text())["cells"]
    main_hw = [c for c in cells if c["hardware"] == "main"]
    geoms = []
    for c in main_hw:
        key = (c["mount"], c["geometry"])
        if key not in geoms:
            geoms.append(key)
    rows, out, worst = [], [], 0.0
    for mount, geom in geoms:
        cs = {c["bw"]: c for c in main_hw if c["mount"] == mount and c["geometry"] == geom}
        c0 = cs["400"]
        state = "both LoS" if geom.startswith("both LoS") else "blocked (" + ", ".join(f"O-RU {i}" for i, b in enumerate(c0["blocked_orus"]) if b) + ")"
        cells_txt = []
        rec = {"mount": mount, "state": state, "ue_x_m": c0["ue_xy"][0], "bandwidths": {}}
        for bw in ("400", "100"):
            c = cs[bw]
            check = abs(c["rmse_m"] ** 2 - c["bias_m"] ** 2 - c["spread_rms_m"] ** 2) / c["rmse_m"] ** 2
            worst = max(worst, check)
            rec["bandwidths"][bw] = {"peb_m": c["peb_los_m"], "bias_m": c["bias_m"], "centred_rms_m": c["spread_rms_m"], "rmse_m": c["rmse_m"],
                                     "centred_to_peb": c["spread_rms_m"] / c["peb_los_m"], "bias_to_rmse": c["bias_m"] / c["rmse_m"], "identity_rel_dev": check}
            cells_txt += [f"{100 * c['peb_los_m']:.1f}", f"{100 * c['bias_m']:.1f}", f"{100 * c['spread_rms_m']:.1f}", f"{100 * c['rmse_m']:.1f}"]
        out.append(rec)
        rows.append(f"{mount} & {state} & {c0['ue_xy'][0]:.1f} & " + " & ".join(cells_txt) + r" \\")
    tex = [f"% Generated by scripts/p2_validation_table.py from results/P2/diag_rmse_vs_peb_{args.set}.json. Do not edit.",
           "% Columns: mount & LoS state & UE x [m] & (400 MHz) PEB & bias & centred RMS & RMSE & (100 MHz) PEB & bias & centred RMS & RMSE; all errors in cm.",
           "% Main hardware (sigma_sync 1 ns, sigma_phi 2 deg), TDoA, 500 single-epoch draws per cell; RMSE^2 = bias^2 + centred^2 holds to "
           f"{worst:.1e} (relative)."] + rows
    (ROOT / "paper2" / "tables").mkdir(parents=True, exist_ok=True)
    (ROOT / "paper2" / "tables" / "validation.tex").write_text("\n".join(tex) + "\n")
    (ROOT / "results" / "P2" / f"validation_table_{args.set}.json").write_text(json.dumps({"definition": __doc__, "rows": out, "identity_max_rel_dev": worst}, indent=1) + "\n")
    print("\n".join(tex))


if __name__ == "__main__":
    main()
