"""Write results/M5/report.md from the M5 result files (no hand-typed numbers)."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R5 = ROOT / "results" / "M5"


def f(x, d=3, scale=1.0):
    return "—" if x is None else f"{x * scale:.{d}f}"


def main() -> None:
    fs = json.loads((R5 / "foresight.json").read_text())
    lt = json.loads((R5 / "leadtime.json").read_text())
    trk = json.loads((R5 / "tracking.json").read_text())
    cat = json.loads((R5 / "numbers_catalog.json").read_text())
    main_tex = (ROOT / "paper" / "main.tex").read_text(encoding="utf-8")
    defaults = dict(re.findall(r"\\providecommand\{\\(num[A-Za-z]+)\}\{\\prelim\{(.*?)\}\}", main_tex))
    numbers = (ROOT / "paper" / "numbers.tex").read_text(encoding="utf-8")
    defined = dict(re.findall(r"\\newcommand\{\\(num[A-Za-z]+)\}\{(.*)\}", numbers))
    L: list[str] = []
    add = L.append
    add("# M5 — Experiments and figures (in review)")
    add("")
    add("Generated by `scripts/report_m5.py`. One command regenerates everything: `python scripts/make_paper.py` "
        "(in the container; `--leadtime-recompute` replays the trackers).")
    add("")
    add("## Outputs")
    add("")
    add("| Output | Script | Source |")
    add("|---|---|---|")
    add("| `paper/tables/tab_blockage.tex` | `fig_blockage_table.py` | cached comm traces, evaluation seeds; tuning-seed run must reproduce `results/M1.5/diversity.json` (it does) |")
    add("| `paper/figs/fig_leadtime.pdf` | `fig_leadtime.py` | M2 detection caches (stage-validated), tracker replay |")
    add("| `paper/figs/fig_onset.pdf` | `fig_onset.py` | `results/M3/onset/onset_events.json` + m3_timeline caches |")
    add("| `paper/figs/fig_outage_margin.pdf` | `fig_outage_margin.py` | `results/M5/planner.json` (A3 wide, A5, planners, instantaneous oracle) + `dporacle.json` (cost-aware oracle, 0.1 s epochs) |")
    add("| `paper/figs/fig_value.pdf` (replaces fig_headroom.pdf) | `fig_value.py` | `results/M5/planner.json` (best reactive = A5, value of foresight by class, planner markers) |")
    add("| `paper/numbers.tex` | `make_paper.py` | `results/M5/numbers_catalog.json` (every macro with value, script, config, seeds, aggregation, raw values) |")
    add("")
    add("## Stage-scoped detection provenance")
    add("")
    add("`sim/sensing/provenance.py` now validates radar detection caches (`detections_<n>.json`) by a stage hash: the `sim/sensing/*.py` "
        "sources (except `provenance.py`, which only reads and writes stamps) plus the sensing part of `configs/m2_scenario.yaml` "
        "(carrier, numerology, subcarriers, `sensing_radar`). Caches without a stage stamp (all current ones) are checked against the stage "
        "hash of the M2 commit `a35536b`. The current tree has the same stage hash, so the caches validate "
        f"(stage checks: {', '.join(lt['stage_checks'])}). Nothing was restamped or rebuilt; the channel-cache (trace) provenance is unchanged.")
    add("")
    add("## Lead time and tracking, recomputed")
    add("")
    add(f"Map tracker retuned on the tuning seeds with the follow-up grid: {lt['tuned_map']} (bus/truck track Pd {lt['tuning_bus_truck_pd']:.3f}); "
        f"identical to `MAP_TUNED`. Lead-time counts: {lt['followup_match']}. Tuning {lt['tune_wall_s'] / 60:.0f} min, evaluation "
        f"{lt['eval_wall_s']:.0f} s (4 CPU workers).")
    add("")
    add("| Variant | Tracker | Track Pd bus/truck | Track Pd pedestrian | FA/CPI | Cross-lane RMSE bus/truck [m/s] |")
    add("|---|---|---|---|---|---|")
    for key, v in trk["variants"].items():
        det, tracker = key.split("|")
        det = "budget 4, no ghost handling" if det == "noghost" else "budget 4, image-method ghosts"
        add(f"| {det} | {tracker} | {f(v['track_pd']['bus/truck'])} | {f(v['track_pd']['pedestrian'])} | {f(v['false_alarms_per_cpi'], 2)} | {f(v['cross_lane_rmse_mps']['bus/truck'], 2)} |")
    add("")
    add("## Foresight bound: methodology change (causal counterfactual)")
    add("")
    add("**Changed in M5 at the reviewer's request.** Old definition (M3 report section 13): A3 wrong-cell time (A3's cell below the "
        "service rate, other cell usable) only inside 10 dB events of the fixed (strongest-unblocked) cell. It missed blockage of the cell "
        "A3 is actually on and sub-10 dB blockage that already causes outage at low margins. New definition (`scripts/run_m5_foresight.py`): "
        "per 10 ms step and lane, wrong-cell time is blockage-caused when A3's cell would be usable with its unblocked power, and "
        "distance-caused when it is unusable even unblocked. The foresight bound is the blockage-caused wrong-cell time (any loss level, "
        "either cell). Both splits of the wrong-cell time sum to the same total (checked), and interruption and both-unusable equal the M3 "
        "decomposition (checked by the former `fig_headroom.py`, which fig_value.py replaced). Shares are POOLED over evaluation jobs (sum of steps / sum of A3 outage steps); "
        "absolute values are means over jobs.")
    add("")
    add("| Margin | A3 outage [s/UE-min] | Old bound [s/UE-min] | Old share | New bound [s/UE-min] | New share | Distance-caused [s/UE-min] | Interruption share | Both unusable share |")
    add("|---|---|---|---|---|---|---|---|---|")
    for r in fs["margins"]:
        add(f"| {r['label']} | {f(r['outage']['s_per_ue_min']['mean'])} | {f(r['old_in_events']['s_per_ue_min']['mean'])} | "
            f"{f(r['old_in_events']['share_of_a3_outage_pooled'], 1, 100)} % | {f(r['new_blockage_caused']['s_per_ue_min']['mean'])} | "
            f"{f(r['new_blockage_caused']['share_of_a3_outage_pooled'], 1, 100)} % | {f(r['new_distance_caused']['s_per_ue_min']['mean'])} | "
            f"{f(r['b_interruption']['share_of_a3_outage_pooled'], 1, 100)} % | {f(r['c_both_unusable']['share_of_a3_outage_pooled'], 1, 100)} % |")
    add("")
    add("Per class (pooled share of A3 outage). Old: by class of the 10 dB event; new: by class of the dominant LoS blocker of A3's cell at that step.")
    add("")
    add("| Margin | Old bus/truck | Old pedestrian | New bus/truck | New pedestrian | New car | New no LoS blocker |")
    add("|---|---|---|---|---|---|---|")
    for r in fs["margins"]:
        o = lambda c: f(r[f"old_in_events|{c}"]["share_of_a3_outage_pooled"], 1, 100) + " %"  # noqa: E731
        n = lambda c: f(r[f"new_blockage_caused|{c}"]["share_of_a3_outage_pooled"], 1, 100) + " %"  # noqa: E731
        add(f"| {r['label']} | {o('bus/truck')} | {o('pedestrian')} | {n('bus/truck')} | {n('pedestrian')} | {n('car')} | {n('no LoS blocker')} |")
    add("")
    dpo = R5 / "dporacle.json"
    if dpo.exists():
        dp = json.loads(dpo.read_text())
        add("## Critical check: cost-aware oracle (upper bound for any foresight policy)")
        add("")
        add("`scripts/run_m5_dporacle.py`. Per lane, a Viterbi over the serving cell in 10 ms steps with perfect knowledge of both cells' "
            "blocked SNR minimises outage at the service rate; every switch costs tau_HO of outage (switches may "
            "start from any state, as in the simulator); initial cell free; no sensing overhead. Variants: switches at "
            "any 10 ms step, or only at 0.1 s E2 epochs. Checks: the Viterbi equals an exhaustive search on 2400 random small lanes, and at "
            "tau_HO = 0 with any-step switching it equals the instantaneous oracle at every margin. Outage at the service rate, "
            "s/UE-min, mean ± 95 % CI over 40 evaluation jobs; gap closed = (A3 − cost-aware) / (A3 − instantaneous oracle), pooled.")
        add("")
        for t, name in (("0.020", "tau_HO = 20 ms"), ("0.000", "tau_HO = 0 (A3 and genies retuned at 0)")):
            add(f"### {name}")
            add("")
            add("| Margin | A3 | Genie (1st policy, no ovh.) | Onset genie (no ovh.) | Cost-aware, any step | Cost-aware, 0.1 s epochs | Instantaneous oracle | Gap closed (any / epochs) |")
            add("|---|---|---|---|---|---|---|---|")
            ci = lambda x: "—" if x is None or x.get("mean") is None else f"{x['mean']:.3f} ± {x['ci']:.3f}"  # noqa: E731
            pc = lambda x: "—" if x is None else f"{100 * x:.0f} %"  # noqa: E731
            for r in dp["margins"]:
                b = r[t]
                add(f"| {r['label']} | {ci(b['a3'])} | {ci(b['genie_no_overhead'])} | {ci(b['onset_genie_no_overhead'])} | {ci(b['costaware_any'])} | "
                    f"{ci(b['costaware_epoch'])} | {ci(b['oracle_inst'])} | {pc(b['costaware_any_gap_closed_pooled'])} / {pc(b['costaware_epoch_gap_closed_pooled'])} |")
            add("")
        add("Gap closed by the cost-aware oracle (any step, tau_HO = 20 ms) split by blocker class: net steps (A3 in outage and the oracle "
            "not, minus the reverse) by the dominant LoS blocker of A3's cell at that step, as a share of the A3-oracle gap (pooled).")
        add("")
        add("| Margin | bus/truck | pedestrian | car | no LoS blocker | total |")
        add("|---|---|---|---|---|---|")
        for r in dp["margins"]:
            byc = r["0.020"]["costaware_any_gap_closed_by_class_pooled"]
            if byc["bus/truck"] is None:
                continue
            add(f"| {r['label']} | " + " | ".join(f"{100 * byc[c]:.1f} %" for c in ("bus/truck", "pedestrian", "car", "no LoS blocker"))
                + f" | {100 * r['0.020']['costaware_any_gap_closed_pooled']:.1f} % |")
        add("")
        add("A3-oracle gap shares (pooled; `foresight.json` `a3_oracle_gap_pooled`): foresight-recoverable (blockage-caused wrong cell), "
            "distance-caused wrong cell, interruption.")
        add("")
        add("| Margin | Gap [s/UE-min] | Foresight-recoverable | Distance-caused | Interruption | Cost-aware closes |")
        add("|---|---|---|---|---|---|")
        for r, d in zip(fs["margins"], dp["margins"]):
            g = r["a3_oracle_gap_pooled"]
            pc = lambda x: "—" if x is None else f"{100 * x:.0f} %"  # noqa: E731
            add(f"| {r['label']} | {g['gap_s_per_ue_min_pooled']:.3f} | {pc(g['foresight_recoverable_share'])} | {pc(g['distance_caused_share'])} | "
                f"{pc(g['interruption_share'])} | {pc(d['0.020']['costaware_any_gap_closed_pooled'])} |")
        add("")
        add("Reading: the cost-aware oracle closes far more of the gap than the foresight-recoverable share alone, most visibly at high "
            "margins where interruption dominates. A3's interruption time is not unavoidable: a policy that knows the future SNR of both "
            "cells avoids most of A3's handovers (and the switching they cost) and still serves the blockages. The genie with the "
            "first-round and onset-advance policies realises none of this (it does not beat A3 within the CIs).")
        add("")
        r10 = next(r for r in dp["margins"] if r["label"] == "10 dB")["0.020"]["genie_trigger_diagnosis"]
        n = max(r10["n"], 1)
        add("### Genie diagnosis at 10 dB")
        add("")
        add(f"Of {r10['n']} blockage-caused wrong-cell steps of A3 (A3's cell unusable, other usable, A3's cell usable unblocked): "
            f"{r10['los_lt10']} ({100 * r10['los_lt10'] / n:.0f} %) have LoS loss < 10 dB on A3's cell; {r10['other_ge3_usable']} "
            f"({100 * r10['other_ge3_usable'] / n:.0f} %) have the other cell at >= 3 dB LoS loss but still usable; {r10['either']} "
            f"({100 * r10['either'] / n:.0f} %) meet at least one of the two and are outside the genie's trigger (serving LoS >= 10 dB, other "
            f"< 3 dB); {r10['both_conditions_met']} ({100 * r10['both_conditions_met'] / n:.0f} %) satisfy both trigger conditions. All margins "
            "are in `dporacle.json` (`genie_trigger_diagnosis`).")
        add("")
    pl = R5 / "planner.json"
    if pl.exists():
        P = json.loads(pl.read_text())
        ci = lambda x: "—" if x is None or x.get("mean") is None else f"{x['mean']:.3f} ± {x['ci']:.3f}"  # noqa: E731
        add("## Equal-effort reactive baselines and a receding-horizon planner")
        add("")
        add("**Added after the cost-aware-oracle result** (`scripts/run_m5_planner.py`). Tuning on tuning seeds per margin, evaluation "
            "on evaluation seeds, tau_HO 20 ms, E2 delay 20 ms. A3 (wide): offset {0,1,3,6,10,15} dB x hysteresis {0,1,3,6,10,15} dB x TTT "
            "{40..640} ms (180 points). A5: serving filtered SNR < SNR_req + t1 and neighbour > SNR_req + t2 for TTT, t1 {-3,0,3,6,10} dB x "
            "t2 {0,3,6,10} dB x TTT {40..640} ms (100 points); A5 was added to the simulator with a vectorised-vs-reference equality test, "
            "and the existing schemes are unchanged (regression identical). Best reactive = lower tuning objective. Planner (xApp v2): "
            "at each 0.1 s report, from the current cell, a Viterbi over horizon H on predicted SNR of both cells (switches only at future "
            "0.1 s epochs, switch = tau_HO outage), first decision applied after the E2 delay; no A3 underneath, no hold. Genie-planner: "
            "true future blocked SNR, no overhead. Sensing-planner: unblocked SNR along the UE path (digital-twin radio map) minus the "
            "predicted model-B LoS loss of the tracked blockers (final M2 map tracker, budget 2 or 4 tuned per H, UE fix sigma 1 m), "
            "overhead charged. Diagnostic (not a policy): the sensing-planner model with the true LoS loss, overhead charged. The "
            "planner's first decision equals an exhaustive search on 300 random small cases.")
        add("")
        add("### Tuned reactive parameters (tuning seeds)")
        add("")
        add("| Margin | A3 wide offset/hyst/TTT | A5 t1/t2/TTT | Best reactive | Genie-planner tuned H | Sensing-planner tuned H (budget) |")
        add("|---|---|---|---|---|---|")
        for r in P["margins"]:
            a, b5 = r["a3_wide"]["params"], r["a5"]["params"]
            sh = f"{r['sensing_planner_tuned_H']:.1f}"
            add(f"| {r['label']} | {a['offset_db']:.0f}/{a['hysteresis_db']:.0f}/{a['ttt_s'] * 1e3:.0f} | {b5['t1_db']:.0f}/{b5['t2_db']:.0f}/{b5['ttt_s'] * 1e3:.0f} | "
                f"{r['best_reactive']} | {r['genie_planner_tuned_H']:.1f} s | {sh} s ({r['sensing_planner'][sh]['budget']}) |")
        add("")
        add("### Value of foresight (best reactive vs cost-aware oracle, any-step switching, tau_HO 20 ms; changed after review A1)")
        add("")
        add("| Margin | Best reactive | Cost-aware | Difference [s/UE-min] | Share of best-reactive gap | bus/truck | pedestrian | car |")
        add("|---|---|---|---|---|---|---|---|")
        for r in P["margins"]:
            v = r["value_of_foresight"]
            bc = v["by_class_share_of_gap_pooled"]
            pc = lambda x: "—" if x is None else f"{100 * x:.0f} %"  # noqa: E731
            add(f"| {r['label']} | {ci(r[r['best_reactive']]['eval']['outage_req_s_per_min'])} | {ci(v['costaware'])} | "
                f"{v['best_reactive_minus_costaware_s_per_ue_min']:.3f} | {pc(v['share_of_best_reactive_gap_pooled'])} | {pc(bc['bus/truck'])} | "
                f"{pc(bc['pedestrian'])} | {pc(bc['car'])} |")
        add("")
        add("Share = (best reactive − cost-aware) / (best reactive − instantaneous oracle), pooled steps; class = dominant LoS blocker of the "
            "best reactive scheme's cell (net steps).")
        add("")
        add("### Per-margin results (evaluation seeds; outage at the service rate [s/UE-min], mean ± 95 % CI over 40 jobs)")
        add("")
        dpj = json.loads((R5 / "dporacle.json").read_text())
        for r, dr in zip(P["margins"], dpj["margins"]):
            add(f"#### {r['label']}")
            add("")
            add("| Scheme | Outage_req | HO / UE-min | Ping-pong |")
            add("|---|---|---|---|")
            row = lambda name, agg: add(f"| {name} | {ci(agg['outage_req_s_per_min'])} | {ci(agg['ho_per_min'])} | {ci(agg['ping_pong'])} |")  # noqa: E731
            row("A3 (wide grid)", r["a3_wide"]["eval"])
            row("A5", r["a5"]["eval"])
            add(f"| best reactive = {r['best_reactive']} | (as above) | | |")
            for h, v in r["genie_planner"].items():
                row(f"genie-planner, H = {h} s" + (" (tuned)" if float(h) == r["genie_planner_tuned_H"] else ""), v["eval"])
            for h, v in r["sensing_planner"].items():
                row(f"sensing-planner, H = {h} s, budget {v['budget']}" + (" (tuned)" if float(h) == r["sensing_planner_tuned_H"] else ""), v["eval"])
            for h, v in r["diag_trueloss_planner"].items():
                row(f"diagnostic: true-LoS-loss planner, H = {h} s", v["eval"])
            add(f"| cost-aware oracle (any step) | {ci(dr['0.020']['costaware_any'])} | — | — |")
            add(f"| cost-aware oracle (0.1 s epochs; not a bound for the planners) | {ci(dr['0.020']['costaware_epoch'])} | — | — |")
            add(f"| instantaneous oracle | {ci(r['oracle_inst']['outage_req_s_per_min'])} | 0 | 0 |")
            add("")
        tl_rows = [(k, v) for k, v in cat.items() if k.startswith("x.trueloss_vs_a5.")]
        if tl_rows:
            add("True-LoS-loss planner vs A5 from 15 dB up (sensing-planner's tuned H; 95 % CI = 1.96 sd / sqrt(40) over evaluation jobs):")
            add("")
            add("| Margin | True-LoS-loss planner | A5 | 95 % CIs overlap |")
            add("|---|---|---|---|")
            for k, v in tl_rows:
                t_, a_ = v["raw"]["trueloss"], v["raw"]["a5"]
                lab = k.split(".")[2]
                add(f"| {lab} | {t_['mean']:.3f} ± {t_['ci']:.3f} | {a_['mean']:.3f} ± {a_['ci']:.3f} | {v['value']} |")
            add("")
            add("The true-LoS-loss planner's mean outage is below A5's at every margin from 15 dB up, but the 95 % CIs overlap at "
                + ("every one of these margins" if all(v["value"] == "yes" for _, v in tl_rows) else "some of these margins")
                + " (unpaired comparison over jobs); 'beats A5' refers to the means.")
            add("")
        pjf = R5 / "paired.json"
        if pjf.exists():
            pj = json.loads(pjf.read_text())
            add("Paired comparison on the same 40 evaluation jobs (`scripts/run_m5_paired.py`; statistics only). d = scheme − A5 per job "
                "[s/UE-min] (each job = mean over its UEs); mean with t-based 95 % CI (39 dof); two-sided Wilcoxon signed-rank p (zero "
                "differences dropped); negative = lower outage than A5. Not corrected for multiple comparisons.")
            add("")
            add("| Margin | H [s] | True-LoS-loss − A5: mean [95 % CI] | p | lower / higher jobs | Sensing − A5: mean [95 % CI] | p | lower / higher jobs |")
            add("|---|---|---|---|---|---|---|---|")
            for r in pj["margins"]:
                t_, s_ = r["trueloss_vs_a5"], r["sensing_vs_a5"]
                add(f"| {r['label']} | {r['H_s']:.1f} | {t_['mean_diff']:+.3f} [{t_['ci95'][0]:+.3f}, {t_['ci95'][1]:+.3f}] | {t_['wilcoxon_p_two_sided']:.2g} | "
                    f"{t_['n_scheme_lower']} / {t_['n_scheme_higher']} | {s_['mean_diff']:+.3f} [{s_['ci95'][0]:+.3f}, {s_['ci95'][1]:+.3f}] | "
                    f"{s_['wilcoxon_p_two_sided']:.2g} | {s_['n_scheme_lower']} / {s_['n_scheme_higher']} |")
            add("")
            sig = [r["label"] for r in pj["margins"] if r["trueloss_vs_a5"]["ci95"][1] < 0 and r["trueloss_vs_a5"]["wilcoxon_p_two_sided"] < 0.05]
            add("Paired, the true-LoS-loss planner has significantly lower outage than A5 (CI below 0 and p < 0.05) at: "
                + (", ".join(sig) if sig else "no margin") + ". The unpaired CIs above overlap because the job-to-job spread is large, "
                "while the per-job differences are consistent. The sensing-planner is significantly worse than A5 wherever its CI excludes 0.")
            add("")
        add("Reading (planner): the genie-planner reaches the cost-aware bound at every margin, and the horizon hardly matters (0.5 s "
            "suffices). The sensing-planner is worse than the best reactive scheme at every margin. The true-LoS-loss diagnostic separates "
            "the causes: with perfect blockage prediction the same planner model has a lower mean outage than the best reactive scheme at margins >= 15 dB even "
            "with the sensing overhead, and loses at 0-10 dB (overhead and the 'unblocked SNR minus LoS loss' approximation). The gap "
            "between the diagnostic and the sensing-planner is the blockage-prediction error of the current tracker/predictor (false "
            "and missed blockages, no measurement feedback in the plan as specified).")
        add("")
    a1f, a34f, ltf = R5 / "review_a1.json", R5 / "review_a34.json", R5 / "leadtime_final.json"
    if a1f.exists():
        add("## External review, block A (correctness) -- ADDED AFTER REVIEW")
        add("")
        a1 = json.loads(a1f.read_text())
        add("### A1 Oracle accounting (`scripts/review_a1_oracle.py`)")
        add("")
        add("The simulator counts outage at the service rate as the UNION of handover interruption and rate below the service rate "
            "(`outage = interrupted | rate < req`; an interrupted step counts once). The cost-aware Viterbi uses the same union objective "
            "(state = cell and remaining interruption steps; an interrupted step costs 1 regardless of SNR). Per evaluation job and margin, "
            "every scheme was compared with the cost-aware oracle (tau_HO 20 ms).")
        add("")
        add("| Margin | Any-step oracle | 0.1 s-epoch oracle | Instantaneous | Jobs below the any-step oracle (all schemes) | Jobs below the epoch oracle |")
        add("|---|---|---|---|---|---|")
        for r in a1["margins"]:
            below_any = sum(len(c["jobs_below_anystep_oracle"]) for c in r["checks"].values())
            below_ep = {n: c["jobs_below_epoch_oracle"] for n, c in r["checks"].items() if c["jobs_below_epoch_oracle"]}
            add(f"| {r['label']} | {r['oracle_any_mean']:.3f} | {r['oracle_epoch_mean']:.3f} | {r['instantaneous_mean']:.3f} | {below_any} | "
                + (", ".join(f"{n}: {k}" for n, k in below_ep.items()) or "0") + " |")
        add("")
        add("Result: no scheme beats the any-step cost-aware oracle on any job at any margin, and instantaneous <= any-step <= epoch holds "
            "on every job. The 0.1 s-epoch oracle (switches at k mod 10 = 0) is NOT a bound for the planners, whose switches fall on the "
            "E2-delay-offset grid (k mod 10 = 3); the genie-planner and the true-LoS-loss planner beat it on a few jobs. Fix: the any-step "
            "oracle is now 'the cost-aware oracle' in fig_outage_margin, fig_value, the value-of-foresight shares and the macros "
            "(\\numCostOracle*, \\numValue*, \\numPlanHorizon). The planner re-run changed only the value-of-foresight field; every "
            "other field of planner.json is identical.")
        add("")
    if ltf.exists():
        lt2 = json.loads(ltf.read_text())
        add("### A2 Lead-time detector configuration")
        add("")
        add(f"fig_leadtime.pdf now uses the final detector configuration, the same as the Pd/FA/lead macros: {lt2['config']} (source "
            "`results/M5/tracking.json`). The earlier no-ghost comparison stays available (`fig_leadtime.py --config noghost`) and "
            "still reproduces results/M2/followup.md. \\numMapBus/\\numMapPed/\\numMapCross remain the no-ghost budget-4 detector, as "
            "stated in the catalog.")
        add("")
        add("| Tracker | Class | Events | Confirmed track 0.5 s before onset | Wilson 95 % | lamppost | facade |")
        add("|---|---|---|---|---|---|---|")
        i5 = lt2["leads_s"].index(0.5)
        for k, v in lt2["series"].items():
            tr, cls = k.split("|")
            add(f"| {tr} | {cls} | {v['n']} | {100 * v['share'][i5]:.1f} % | {100 * v['wilson95'][i5][0]:.1f}-{100 * v['wilson95'][i5][1]:.1f} % | "
                + " | ".join(f"{b['hits'][i5]}/{b['n']}" for b in v["by_mount"].values()) + " |")
        add("")
    if a34f.exists():
        a34 = json.loads(a34f.read_text())
        add("### A3 Car share of the closable gap (fig_value)")
        add("")
        add("Net closed steps (A5 vs any-step oracle) by the dominant LoS blocker of A5's cell, as a share of the A5-to-oracle gap (pooled); "
            "and the part of the car-attributed share that comes from LoS losses below 10 dB on A5's cell.")
        add("")
        add("| Margin | Car share of gap | Car share from < 10 dB loss |")
        add("|---|---|---|")
        for r in a34["a3_car_share"]:
            cs = r["shares_of_gap"]["car"]
            sub = r["car_sub10_share_of_car"]
            add(f"| {r['label']} | {'—' if cs is None else f'{100 * cs:+.1f} %'} | {'—' if sub is None else f'{100 * sub:.0f} %'} |")
        add("")
        add("Cars never cause 10 dB events; all car-attributed closable gap comes from sub-10 dB LoS losses (A5 sits below the service rate "
            "while the other cell is usable). Negative shares are net losses of the oracle path on car-attributed steps and are not drawn "
            "in fig_value.")
        add("")
        add("### A4 Onset at 1 ms (analytic model B on the LoS segment, no re-trace)")
        add("")
        add("| Class | Events | Median 10-90 % onset at 1 ms | p10 / p90 at 1 ms | Median at 10 ms (same events) | Onsets below 10 ms at 1 ms |")
        add("|---|---|---|---|---|---|")
        for cls, v in a34["a4_onset"]["summary"].items():
            add(f"| {cls} | {v['n_events']} | {1000 * v['median_1ms_s']:.1f} ms | {1000 * v['p10_p90_1ms_s'][0]:.1f} / {1000 * v['p10_p90_1ms_s'][1]:.1f} ms | "
                f"{1000 * v['median_10ms_s']:.0f} ms | {100 * v['share_below_10ms_at_1ms']:.0f} % |")
        add("")
        add("The bus/truck onset is resolved at 10 ms (median 0.49 s at 1 ms vs 0.50 s). The pedestrian median equals the time step at both "
            "resolutions (1 ms and 10 ms): with the model-B screen of a 0.5 m pedestrian the LoS loss is effectively a step; the onset is "
            "below the 1 ms resolution, i.e. 'abrupt' is a property of the model, not a measured rise time.")
        add("")
    gof = R5 / "grid_oracle.json"
    if gof.exists():
        go = json.loads(gof.read_text())
        add("## After block A review: grid-aligned cost-aware oracle -- ADDED AFTER REVIEW")
        add("")
        add(f"`scripts/review_grid_oracle.py`. Same Viterbi (union objective, tau_HO 20 ms), switches only on the planner's decision grid "
            f"(k mod {go['grid']['epoch_steps']} = {go['grid']['offset_steps']}, i.e. 0.1 s epochs offset by the E2 delay + 10 ms). The any-step "
            "oracle stays THE bound; the grid-aligned oracle is the bound for policies that act only at E2 decision epochs and is used for "
            "\\numPlanHorizon. Checks: instantaneous <= any-step <= grid-aligned on every job; no planner (any H) beats the grid-aligned "
            "oracle on any job.")
        add("")
        add("| Margin | Any-step | Grid-aligned | Grid cost | Instantaneous | Planner jobs below grid oracle |")
        add("|---|---|---|---|---|---|")
        for r in go["margins"]:
            nv = sum(len(v) for v in r["planner_jobs_below_grid_oracle"].values())
            add(f"| {r['label']} | {r['any']['mean']:.3f} | {r['grid']['mean']:.3f} | +{100 * r['grid_cost_rel']:.1f} % | {r['inst']['mean']:.3f} | {nv} |")
        add("")
    b5f, b6f, b6d, c8f = R5 / "review_b5.json", R5 / "review_b6.json", R5 / "review_b6_diag.json", R5 / "review_c8.json"
    if b5f.exists():
        b5 = json.loads(b5f.read_text())
        add("## External review, block B -- ADDED AFTER REVIEW")
        add("")
        add("### B5 Error-injection ablation of the planner's blockage prediction (`scripts/review_b5_ablation.py`; diagnostic)")
        add("")
        m = b5["measured"]
        add("Planner = the sensing-planner model (unblocked SNR minus predicted LoS loss, overhead charged, H tuned per margin and condition "
            "on tuning seeds); tracks = ground truth at each report (true positions, velocities, sizes; constant-velocity extrapolation), "
            "then one error type injected. Measured final-tracker rates (image ghosts, budget 4, map tracker): miss = 1 - track Pd "
            + ", ".join(f"{c} {100 * v:.0f} %" for c, v in m["miss"].items())
            + f"; false confirmed tracks {m['false_tracks_per_cpi']:.1f} per CPI; position sigma per axis "
            + ", ".join(f"{c} {v:.2f} m" for c, v in m["pos_axis"].items()) + "; velocity sigma per axis "
            + ", ".join(f"{c} {v:.2f} m/s" for c, v in m["vel_axis"].items())
            + ". Spurious tracks are bus boxes on a random lane or pedestrian boxes on a random sidewalk (1/2 each) at a uniform position, "
            "independent per report (assumption). Cells: mean outage [s/UE-min] and the paired difference to A5 "
            "(mean per-job difference, * = 95 % CI excludes 0 and Wilcoxon p < 0.05).")
        add("")
        labs = [mm["label"] for mm in next(iter(b5["conditions"].values()))["margins"]]
        short = lambda lab_: {"3GPP short-range reference": "ref", "v1 radio (high margin)": "v1"}.get(lab_, lab_)  # noqa: E731
        add("| Condition | " + " | ".join(short(x) for x in labs) + " |")
        add("|---|" + "---|" * len(labs))
        for cname, c in b5["conditions"].items():
            cells = []
            for mm in c["margins"]:
                v = mm["vs_a5"]
                star = "*" if (v["ci95"][0] > 0 or v["ci95"][1] < 0) and v["wilcoxon_p_two_sided"] < 0.05 else ""
                cells.append(f"{mm['eval']['outage_req_s_per_min']['mean']:.3f} ({v['mean_diff']:+.3f}{star})")
            add(f"| {cname} | " + " | ".join(cells) + " |")
        add("")
        single = ("miss measured", "spurious 1x", "noise measured")
        if all(n in b5["conditions"] for n in single + ("combined measured",)):
            add("Which error type drives the collapse? Each error alone at its measured rate (paired mean difference to A5, s/UE-min):")
            add("")
            add("| Margin | miss (measured) | spurious (1x measured) | position/velocity noise (measured) | sum of the three | combined (measured) | largest single |")
            add("|---|---|---|---|---|---|---|")
            for i, lab_ in enumerate(labs):
                v = {n: b5["conditions"][n]["margins"][i]["vs_a5"]["mean_diff"] for n in single + ("combined measured",)}
                top = max(single, key=lambda n: v[n])
                add(f"| {lab_} | {v['miss measured']:+.3f} | {v['spurious 1x']:+.3f} | {v['noise measured']:+.3f} | {sum(v[n] for n in single):+.3f} | "
                    f"{v['combined measured']:+.3f} | {top} |")
            add("")
            add("At 0-5 dB every condition pays about the same sensing-overhead penalty (cf. B6 diagnostic: A5 + overhead). From 10 dB up the "
                "single measured errors rank as in the last column; the combined case exceeds the sum of the singles at mid margins. "
                "With perfect tracks (baseline) the planner beats A5 from 15 dB up; this is lost already at miss 0.1-0.2, spurious 1x or "
                "0.5 m / 0.5 m/s noise.")
            add("")
    if b6f.exists():
        b6 = json.loads(b6f.read_text())
        add("### B6 Robust planner (post-review baseline, `scripts/review_b6_robust.py`)")
        add("")
        add("A5 runs by default; at each E2 decision epoch the planner may only ADVANCE a handover (plan switches and the serving cell is "
            "predicted >= 10 dB blocked within H) or VETO A5 until the next epoch (plan stays and the other cell is predicted >= 10 dB "
            "blocked within H), using only confirmed map-tracker tracks older than T_c; sensing overhead charged. Tuned per margin on "
            "tuning seeds over T_c {0.3, 0.5, 1, 2} s x H {0.5, 1, 2} s x budget {2, 4}. Simulator support (planner mask, veto) has a "
            f"vectorised-vs-reference equality test; existing schemes unchanged. T_c = 0 predictions match the cached M3 predictions within "
            f"{max(b6['tc0_check_max_abs_db'].values()):.1e} dB (BLAS thread count differs in the replay).")
        add("")
        add("| Margin | Tuned T_c / H / budget | Robust planner | A5 | Paired diff [95 % CI] | Wilcoxon p | HO / UE-min |")
        add("|---|---|---|---|---|---|---|")
        a5m = {r["label"]: r["a5"]["eval"]["outage_req_s_per_min"]["mean"] for r in P["margins"]} if pl.exists() else {}
        for r in b6["margins"]:
            v = r["vs_a5"]
            t_ = r["tuned"]
            add(f"| {r['label']} | {t_['T_c_s']:.1f} s / {t_['H_s']:.1f} s / {t_['budget']} | {r['eval']['outage_req_s_per_min']['mean']:.3f} | "
                f"{a5m.get(r['label'], float('nan')):.3f} | {v['mean_diff']:+.4f} [{v['ci95'][0]:+.4f}, {v['ci95'][1]:+.4f}] | {v['wilcoxon_p_two_sided']:.2g} | "
                f"{r['eval']['ho_per_min']['mean']:.1f} |")
        add("")
        if b6d.exists():
            dg = json.loads(b6d.read_text())
            add("Diagnostic (tuned parameters, evaluation seeds; paired difference to A5 in brackets): which part of the robust planner loses?")
            add("")
            names = ["A5 + overhead", "advance only", "veto only", "advance + veto (check)"]
            add("| Margin | " + " | ".join(names) + " |")
            add("|---|" + "---|" * len(names))
            for r in dg["margins"]:
                add(f"| {r['label']} | " + " | ".join(f"{r[n]['outage_mean']:.3f} ({r[n]['vs_a5']['mean_diff']:+.3f})" for n in names) + " |")
            add("")
    if c8f.exists():
        c8 = json.loads(c8f.read_text())
        add("## External review, block C -- ADDED AFTER REVIEW")
        add("")
        add("C7: \\numRelRedTen / \\numAbsRedTen / \\numRelRedRef / \\numAbsRedRef = A5 -> any-step cost-aware oracle reduction "
            "(see the macro table below).")
        add("")
        add("### C8 Main results by traffic density (`scripts/review_c8_density.py`; 20 evaluation jobs per density; mean ± 95 % CI)")
        add("")
        for r in c8["margins"]:
            if r["label"] not in ("10 dB", "20 dB", "3GPP short-range reference"):
                continue
            add(f"#### {r['label']}")
            add("")
            names = [n for n in r["density"]["low"] if n != "A5 -> any-step oracle"]
            add("| Scheme | low | high |")
            add("|---|---|---|")
            for n in names:
                lo, hi = r["density"]["low"][n], r["density"]["high"][n]
                add(f"| {n} | {lo['mean']:.3f} ± {lo['ci']:.3f} | {hi['mean']:.3f} ± {hi['ci']:.3f} |")
            lo, hi = r["density"]["low"]["A5 -> any-step oracle"], r["density"]["high"]["A5 -> any-step oracle"]
            add(f"| A5 -> any-step oracle reduction | {lo['mean_reduction']:.3f} ± {lo['ci95_half_t']:.3f} ({100 * lo['share_of_a5']:.0f} % of A5) | "
                f"{hi['mean_reduction']:.3f} ± {hi['ci95_half_t']:.3f} ({100 * hi['share_of_a5']:.0f} % of A5) |")
            add("")
        add("All margins are in `results/M5/review_c8.json`.")
        add("")
    add("## paper/numbers.tex vs the defaults in main.tex")
    add("")
    missing = [m for m in defaults if m not in defined]
    add(f"main.tex lists {len(defaults)} macros; numbers.tex defines {len(defined)}. Not defined: {', '.join(missing) if missing else 'none'}.")
    add("")
    add("| Macro | main.tex default (blue) | numbers.tex | Source script | Aggregation |")
    add("|---|---|---|---|---|")
    for m, dv in defaults.items():
        c = cat.get(m, {})
        flag = "" if defined.get(m) == dv else " **changed**"
        add(f"| `\\{m}` | {dv} | {defined.get(m, '—')}{flag} | {c.get('script', '—').split(' ->')[0]} | {c.get('aggregation', '—')} |")
    add("")
    extra = [m for m in defined if m not in defaults]
    if extra:
        add("")
        add("Extra macros (added after the planner round; not in the main.tex header list, defined in numbers.tex):")
        add("")
        add("| Macro | numbers.tex | Source script | Aggregation | Note |")
        add("|---|---|---|---|---|")
        for m in extra:
            c = cat.get(m, {})
            add(f"| `\\{m}` | {defined[m]} | {c.get('script', '—').split(' ->')[0]} | {c.get('aggregation', '—')} | {c.get('note', '')} |")
    add("")
    add("Every macro's full source (script, config incl. detector budget, ghost method and tracker, seeds, aggregation, raw values, notes) "
        "is in `results/M5/numbers_catalog.json`.")
    add("")
    add("## Open items")
    add("")
    add("- LaTeX (latexmk) is not installed in the container or on the host, and `paper/IEEEtran.cls` / `IEEEtran.bst` are not in the "
        "repository; `make_paper.py` prints `cd paper && latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex` instead of compiling.")
    add("- Class shares changed most against the defaults: the defaults were M1 values (one O-RU, tuning seeds); the new values follow the "
        "main.tex definition (two-O-RU config, evaluation seeds, serving cell = strongest unblocked).")
    (R5 / "report.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {R5 / 'report.md'}")


if __name__ == "__main__":
    main()
