"""Write results/M5/report.md from the M5 result files (no hand-typed numbers)."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R5 = ROOT / "results" / "M5"


def f(x, d=3, scale=1.0):
    return "—" if x is None else f"{x * scale:.{d}f}"


def main() -> None:
    fs = json.loads((R5 / "foresight.json").read_text())
    lt = json.loads((R5 / "leadtime.json").read_text())
    trk = json.loads((R5 / "tracking.json").read_text())
    cat = json.loads((R5 / "numbers_catalog.json").read_text())
    main_tex = (ROOT / "paper" / "main.tex").read_text(encoding="utf-8")
    defaults = dict(re.findall(r"\\providecommand\{\\(num[A-Za-z]+)\}\{\\prelim\{(.*?)\}\}", main_tex))
    numbers = (ROOT / "paper" / "numbers.tex").read_text(encoding="utf-8")
    defined = dict(re.findall(r"\\newcommand\{\\(num[A-Za-z]+)\}\{(.*)\}", numbers))
    L: list[str] = []
    add = L.append
    add("# M5 — Experiments and figures (in review)")
    add("")
    add("Generated by `scripts/report_m5.py`. One command regenerates everything: `python scripts/make_paper.py` "
        "(in the container; `--leadtime-recompute` replays the trackers).")
    add("")
    add("## Outputs")
    add("")
    add("| Output | Script | Source |")
    add("|---|---|---|")
    add("| `paper/tables/tab_blockage.tex` | `fig_blockage_table.py` | cached comm traces, evaluation seeds; tuning-seed run must reproduce `results/M1.5/diversity.json` (it does) |")
    add("| `paper/figs/fig_leadtime.pdf` | `fig_leadtime.py` | M2 detection caches (stage-validated), tracker replay |")
    add("| `paper/figs/fig_onset.pdf` | `fig_onset.py` | `results/M3/onset/onset_events.json` + m3_timeline caches |")
    add("| `paper/figs/fig_outage_margin.pdf` | `fig_outage_margin.py` | `results/M3/{metrics,hybrid,genie}.json` |")
    add("| `paper/figs/fig_headroom.pdf` | `fig_headroom.py` | `results/M5/foresight.json` (causal decomposition) + `results/M3/genie.json` (tau_HO = 0) |")
    add("| `paper/numbers.tex` | `make_paper.py` | `results/M5/numbers_catalog.json` (every macro with value, script, config, seeds, aggregation, raw values) |")
    add("")
    add("## Stage-scoped detection provenance")
    add("")
    add("`sim/sensing/provenance.py` now validates radar detection caches (`detections_<n>.json`) by a stage hash: the `sim/sensing/*.py` "
        "sources (except `provenance.py`, which only reads and writes stamps) plus the sensing part of `configs/m2_scenario.yaml` "
        "(carrier, numerology, subcarriers, `sensing_radar`). Caches without a stage stamp (all current ones) are checked against the stage "
        "hash of the M2 commit `a35536b`. The current tree has the same stage hash, so the caches validate "
        f"(stage checks: {', '.join(lt['stage_checks'])}). Nothing was restamped or rebuilt; the channel-cache (trace) provenance is unchanged.")
    add("")
    add("## Lead time and tracking, recomputed")
    add("")
    add(f"Map tracker retuned on the tuning seeds with the follow-up grid: {lt['tuned_map']} (bus/truck track Pd {lt['tuning_bus_truck_pd']:.3f}); "
        f"identical to `MAP_TUNED`. Lead-time counts: {lt['followup_match']}. Tuning {lt['tune_wall_s'] / 60:.0f} min, evaluation "
        f"{lt['eval_wall_s']:.0f} s (4 CPU workers).")
    add("")
    add("| Variant | Tracker | Track Pd bus/truck | Track Pd pedestrian | FA/CPI | Cross-lane RMSE bus/truck [m/s] |")
    add("|---|---|---|---|---|---|")
    for key, v in trk["variants"].items():
        det, tracker = key.split("|")
        det = "budget 4, no ghost handling" if det == "noghost" else "budget 4, image-method ghosts"
        add(f"| {det} | {tracker} | {f(v['track_pd']['bus/truck'])} | {f(v['track_pd']['pedestrian'])} | {f(v['false_alarms_per_cpi'], 2)} | {f(v['cross_lane_rmse_mps']['bus/truck'], 2)} |")
    add("")
    add("## Foresight bound: methodology change (causal counterfactual)")
    add("")
    add("**Changed in M5 at the reviewer's request.** Old definition (M3 report section 13): A3 wrong-cell time (A3's cell below the "
        "service rate, other cell usable) only inside 10 dB events of the fixed (strongest-unblocked) cell. It missed blockage of the cell "
        "A3 is actually on and sub-10 dB blockage that already causes outage at low margins. New definition (`scripts/run_m5_foresight.py`): "
        "per 10 ms step and lane, wrong-cell time is blockage-caused when A3's cell would be usable with its unblocked power, and "
        "distance-caused when it is unusable even unblocked. The foresight bound is the blockage-caused wrong-cell time (any loss level, "
        "either cell). Both splits of the wrong-cell time sum to the same total (checked), and interruption and both-unusable equal the M3 "
        "decomposition (checked in `fig_headroom.py`). Shares are POOLED over evaluation jobs (sum of steps / sum of A3 outage steps); "
        "absolute values are means over jobs.")
    add("")
    add("| Margin | A3 outage [s/UE-min] | Old bound [s/UE-min] | Old share | New bound [s/UE-min] | New share | Distance-caused [s/UE-min] | Interruption share | Both unusable share |")
    add("|---|---|---|---|---|---|---|---|---|")
    for r in fs["margins"]:
        add(f"| {r['label']} | {f(r['outage']['s_per_ue_min']['mean'])} | {f(r['old_in_events']['s_per_ue_min']['mean'])} | "
            f"{f(r['old_in_events']['share_of_a3_outage_pooled'], 1, 100)} % | {f(r['new_blockage_caused']['s_per_ue_min']['mean'])} | "
            f"{f(r['new_blockage_caused']['share_of_a3_outage_pooled'], 1, 100)} % | {f(r['new_distance_caused']['s_per_ue_min']['mean'])} | "
            f"{f(r['b_interruption']['share_of_a3_outage_pooled'], 1, 100)} % | {f(r['c_both_unusable']['share_of_a3_outage_pooled'], 1, 100)} % |")
    add("")
    add("Per class (pooled share of A3 outage). Old: by class of the 10 dB event; new: by class of the dominant LoS blocker of A3's cell at that step.")
    add("")
    add("| Margin | Old bus/truck | Old pedestrian | New bus/truck | New pedestrian | New car | New no LoS blocker |")
    add("|---|---|---|---|---|---|---|")
    for r in fs["margins"]:
        o = lambda c: f(r[f"old_in_events|{c}"]["share_of_a3_outage_pooled"], 1, 100) + " %"  # noqa: E731
        n = lambda c: f(r[f"new_blockage_caused|{c}"]["share_of_a3_outage_pooled"], 1, 100) + " %"  # noqa: E731
        add(f"| {r['label']} | {o('bus/truck')} | {o('pedestrian')} | {n('bus/truck')} | {n('pedestrian')} | {n('car')} | {n('no LoS blocker')} |")
    add("")
    add("## paper/numbers.tex vs the defaults in main.tex")
    add("")
    missing = [m for m in defaults if m not in defined]
    add(f"main.tex lists {len(defaults)} macros; numbers.tex defines {len(defined)}. Not defined: {', '.join(missing) if missing else 'none'}.")
    add("")
    add("| Macro | main.tex default (blue) | numbers.tex | Source script | Aggregation |")
    add("|---|---|---|---|---|")
    for m, dv in defaults.items():
        c = cat.get(m, {})
        flag = "" if defined.get(m) == dv else " **changed**"
        add(f"| `\\{m}` | {dv} | {defined.get(m, '—')}{flag} | {c.get('script', '—').split(' ->')[0]} | {c.get('aggregation', '—')} |")
    add("")
    add("Every macro's full source (script, config incl. detector budget, ghost method and tracker, seeds, aggregation, raw values, notes) "
        "is in `results/M5/numbers_catalog.json`.")
    add("")
    add("## Open items")
    add("")
    add("- LaTeX (latexmk) is not installed in the container or on the host, and `paper/IEEEtran.cls` / `IEEEtran.bst` are not in the "
        "repository; `make_paper.py` prints `cd paper && latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex` instead of compiling.")
    add("- Class shares changed most against the defaults: the defaults were M1 values (one O-RU, tuning seeds); the new values follow the "
        "main.tex definition (two-O-RU config, evaluation seeds, serving cell = strongest unblocked).")
    (R5 / "report.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {R5 / 'report.md'}")


if __name__ == "__main__":
    main()
